name: File Content Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check file contents
      run: |
        if [ -f APP_SPECIFICATION.md ] && grep -q "Boilerplate" APP_SPECIFICATION.md; then
          echo "Please update the 'APP_SPECIFICATION.md' file with your own app data."
          exit 1
        fi
