name: test 2

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Get repos
        id: set-matrix
        run: |
          echo "pouet"
          repo_info_json="[{\"repo\": \"app-u2f\", \"build_directory\": \"./\", \"sdk\": \"C\", \"devices\": \"nanos, nanox, nanos+, stax\"},{\"repo\": \"app-pouet\", \"build_directory\": \"./\", \"sdk\": \"C\", \"devices\": \"nanos, nanox, nanos+, stax\"}]"
          echo "matrix=${repo_info_json}" >> $GITHUB_OUTPUT
          
          # repo_info_json='[{"repo": "app-u2f", "build_directory": "./", "sdk": "C", "devices": "nanos, nanox, nanos+, stax"}, {"repo": "app-pouet", "build_directory": "./", "sdk": "C", "devices": "nanos, nanox, nanos+, stax"}]'
          #echo "matrix=${repo_info_json}" 

  print-matrix2:
    needs: [prepare-matrix]
    runs-on: ubuntu-latest
    steps:
      - name: Print matrix
        run: |
           echo "Matrix content: ${{ needs.prepare-matrix.outputs.matrix }}"

          
  test-build:
    name: Build for all targets
    needs: [prepare-matrix]
    strategy:
      fail-fast: false
    strategy:
      matrix:
        repo: ${{  fromJson(needs.prepare-matrix.outputs.matrix)  }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone App
        uses: actions/checkout@v3
        with:
          repository: LedgerHQ/${{ matrix.Repo }}
          submodules: true

      - name: Build Path
        run: |
          echo "build path"
          echo "build_directory=${{ matrix.build_directory }}" >> $GITHUB_ENV